### PR TITLE
Further improvements in the existing unit test library made

### PR DESCRIPTION
**Pull request by Arash-Sabet**
The reference to full .net version of SharpSimpleNLG in the unit test library has been replaced by a reference to the .net standard version of the library. Also appveyor's yml file added for CI.

### CODE REVIEW

**Comment by nickhodge** [comment]
Thanks Arash-Sabet for updating this.

Please tell me when it is ready for another NuGet, and I will push it out

**Comment by Arash-Sabet** [comment]
You're very welcome. We don't need to roll out a new nuget package because the change is isolated in the test library that has a reference to the core simple nlg library.

**Comment by nickhodge** [comment]
Great.

I've still got to create a correct .NET Standard NuGet

Also, there were 7 tests ported from the original Java that didn't pass in the Java version, so we are matching the upstream source :-)

**Comment by Arash-Sabet** [comment]
There are more than 7 tests that don't pass either. Their failure don't seem to have anything to do with the recent upgrade to net standard. That's why I had to turn off tests in appveyor temporarily.

**Pull request merged**
