### PR TITLE
Upgrading the libraries to .net standard 1.6 and full .net 4.6.2

### PR DESCRIPTION
**Pull request by Arash-Sabet**
I upgraded SharpSimpleNLG to .net standard 1.6 and created a .net core console application to test it out. The console application's code is similar to the original console application shipped in the solution. I was never able to run tests from the time when I forked the solution and since the compilation passes I assume that the tests should pass too. Please verify the changes, merge with the original master and feel free to deploy new nuget packages.

### CODE REVIEW

**Comment by nickhodge** [comment]
I've merged these changes in, and published 1.2.0 onto NuGet. I hope I've done this the correct way. :-)

**Comment by nickhodge** [comment]
@Arash-Sabet AND THANKS for the PR. I hope you are finding this port of the Univ of Aberdeen SimpleNLG useful.

**Comment by Arash-Sabet** [comment]
@nickhodge You are more than welcome! It’s a great and useful library and let’s keep it up-to-date as much as possible. Would you mind reflecting the newer version info in the Version News section of the markdown? Thanks.

**Comment by Arash-Sabet** [comment]
@nickhodge I just checked out [this library's nuget package](https://www.nuget.org/packages/SharpSimpleNLG/); I have to say that the dependencies section needs to be updated to reflect the right versions of .net.

**Pull request merged**
